spring.application.name=customer-management-app

spring.datasource.url=jdbc:postgresql://dpg-daubom2d0e5s73f45k6g-a.singapore-postgres.render.com:5432/customerdb_fpgn
spring.datasource.username=customerdb_fpgn_user
spring.datasource.password=y9eCafaOUQapDoiJlBFVgWXpEPqYaocy

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}